// 맨 위에 이 buildscript 블록을 통째로 추가해 줍니다.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // 우리가 원했던 호환 버전(8.2.0)을 여기에 강제로 주입합니다.
        classpath 'com.android.tools.build:gradle:8.2.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}